import type { Pepper } from "../types/pepper";

export const pepperCrop = {
  items: [
    {
      id: 32,
      name: "Bird's Eye",
      alternateNames: "Thai Bird's Eye, Bird Chili",
      species: "annuum",
      type: "thai_type",
      description: "Tiny but mighty Thai pepper with sharp, immediate heat. Essential in Southeast Asian cooking for stir-fries, curries, and dipping sauces. Plants produce prolifically with upright pods. One of the most widely used hot peppers worldwide.",
      heatSHU_min: 50000,
      heatSHU_max: 100000,
      heatCategory: "hot",
      sweetness: 3,
      fruitiness: 4,
      smokiness: 2,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["cooking", "hot_sauce", "fresh_eating"],
      cuisineAffinity: ["thai", "vietnamese", "malaysian"],
      prepBest: ["raw", "dried", "paste"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "very_high",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 10,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 2,
      lengthCm_max: 4,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "SeedSow",
      vendorVarietyNames: "Pepper (Hot) - Bird's Eye",
    },
    {
      id: 35,
      name: "Thai",
      alternateNames: "Thai Dragon, Thai Hot",
      species: "annuum",
      type: "thai_type",
      description: "The workhorse hot pepper of Southeast Asian cooking. Upright pods on ornamental plants transition through colors as they mature. Sharp, immediate heat that complements rather than overwhelms. Very productive in warm conditions.",
      heatSHU_min: 50000,
      heatSHU_max: 100000,
      heatCategory: "hot",
      sweetness: 3,
      fruitiness: 4,
      smokiness: 2,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["cooking", "hot_sauce", "drying"],
      cuisineAffinity: ["thai", "vietnamese", "asian"],
      prepBest: ["raw", "dried", "paste"],
      daysToMaturity_min: 80,
      daysToMaturity_max: 100,
      plantHeightCm_min: 45,
      plantHeightCm_max: 90,
      growthHabit: "bushy",
      yieldLevel: "very_high",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 8,
      coldTolerance: 3,
      containerFriendly: true,
      minPotLiters: 10,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 3,
      lengthCm_max: 7,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "SeedSow",
      vendorVarietyNames: "Pepper (Hot) - Thai",
    },
    {
      id: 33,
      name: "Tabasco",
      alternateNames: "",
      species: "frutescens",
      type: "other",
      description: "Made famous by the hot sauce brand, but an excellent garden variety. Small, upright pods with thin walls are perfect for fermenting. Sharp, vinegary heat. The original pods have a distinctive 'juicy' quality when bitten.",
      heatSHU_min: 30000,
      heatSHU_max: 50000,
      heatCategory: "hot",
      sweetness: 2,
      fruitiness: 4,
      smokiness: 2,
      bitterness: 3,
      earthiness: 5,
      bestUses: ["hot_sauce", "fermenting", "cooking"],
      cuisineAffinity: ["cajun", "american"],
      prepBest: ["fermented", "vinegar-based", "raw"],
      daysToMaturity_min: 80,
      daysToMaturity_max: 100,
      plantHeightCm_min: 90,
      plantHeightCm_max: 150,
      growthHabit: "tall",
      yieldLevel: "high",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: false,
      minPotLiters: 15,
      indoorSuitable: false,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 5,
      wallThickness: "thin",
      colorStages: ["yellow", "orange", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "SeedSow",
      vendorVarietyNames: "Pepper (Hot) - Tabasco",
    },
    {
      id: 34,
      name: "Tepin",
      alternateNames: "Chiltepin, Bird Pepper, Mother of All Peppers",
      species: "annuum",
      type: "other",
      description: "Considered the wild ancestor of all cultivated peppers. Tiny pea-sized pods pack explosive but short-lived heat - locals say it's like a 'sneeze' of spice. Birds spread the seeds (hence 'bird pepper'). A rare and prized variety.",
      heatSHU_min: 50000,
      heatSHU_max: 100000,
      heatCategory: "hot",
      sweetness: 2,
      fruitiness: 4,
      smokiness: 3,
      bitterness: 3,
      earthiness: 6,
      bestUses: ["cooking", "drying", "hot_sauce"],
      cuisineAffinity: ["mexican", "southwestern"],
      prepBest: ["dried", "crushed", "raw"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 3,
      containerFriendly: true,
      minPotLiters: 12,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 0.5,
      lengthCm_max: 1,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "Slow germination - be patient",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "SeedSow",
      vendorVarietyNames: "Pepper (Hot) - Tepin",
    },
    {
      id: 66,
      name: "Pequin",
      alternateNames: "Piquin, Bird Pepper",
      species: "annuum",
      type: "other",
      description: "Small, bullet-shaped Mexican chile with intense, citrusy heat. Often found crushed as table seasoning in Mexican restaurants. More flavor complexity than similar-sized Asian peppers. Drought-tolerant once established.",
      heatSHU_min: 40000,
      heatSHU_max: 60000,
      heatCategory: "hot",
      sweetness: 2,
      fruitiness: 5,
      smokiness: 3,
      bitterness: 2,
      earthiness: 5,
      bestUses: ["drying", "cooking", "hot_sauce"],
      cuisineAffinity: ["mexican"],
      prepBest: ["dried", "crushed", "raw"],
      daysToMaturity_min: 85,
      daysToMaturity_max: 100,
      plantHeightCm_min: 60,
      plantHeightCm_max: 90,
      growthHabit: "bushy",
      yieldLevel: "high",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 4,
      containerFriendly: true,
      minPotLiters: 10,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 1,
      lengthCm_max: 2,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 67,
      name: "Piri Piri",
      alternateNames: "African Bird's Eye, Peri Peri",
      species: "frutescens",
      type: "other",
      description: "The famous pepper behind Nando's and Portuguese-African cuisine. Small, tapering pods with fruity, citrusy heat. Makes excellent hot sauce and marinades. Name means 'pepper pepper' in Swahili.",
      heatSHU_min: 50000,
      heatSHU_max: 175000,
      heatCategory: "very_hot",
      sweetness: 3,
      fruitiness: 7,
      smokiness: 2,
      bitterness: 2,
      earthiness: 4,
      bestUses: ["hot_sauce", "marinade", "cooking"],
      cuisineAffinity: ["portuguese", "african", "mozambican"],
      prepBest: ["sauce", "marinade", "dried"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "high",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 10,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 2,
      lengthCm_max: 4,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 95,
      name: "Malagueta",
      alternateNames: "Malagueta Pepper",
      species: "frutescens",
      type: "other",
      description: "Brazil's signature hot pepper, essential for feijoada and other traditional dishes. Small, tapered pods with sharp, clean heat. Not to be confused with 'melegueta' (grains of paradise). Widely used in Portuguese-influenced cuisines.",
      heatSHU_min: 60000,
      heatSHU_max: 100000,
      heatCategory: "hot",
      sweetness: 2,
      fruitiness: 4,
      smokiness: 2,
      bitterness: 3,
      earthiness: 5,
      bestUses: ["cooking", "hot_sauce", "marinade"],
      cuisineAffinity: ["brazilian", "portuguese"],
      prepBest: ["fresh", "pickled", "sauce"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "high",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 10,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 2,
      lengthCm_max: 4,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },

    // ===== HABANERO TYPES (100,000-350,000 SHU) =====
    {
      id: 36,
      name: "Habanero",
      alternateNames: "Habanero Orange",
      species: "chinense",
      type: "habanero_type",
      description: "The classic very hot pepper that introduced many to extreme heat. Lantern-shaped pods with distinctively fruity, floral flavor beneath the intense burn. Essential for Caribbean jerk and tropical hot sauces. Longer season required.",
      heatSHU_min: 100000,
      heatSHU_max: 350000,
      heatCategory: "very_hot",
      sweetness: 4,
      fruitiness: 8,
      smokiness: 2,
      bitterness: 3,
      earthiness: 3,
      bestUses: ["hot_sauce", "cooking", "fermenting"],
      cuisineAffinity: ["caribbean", "mexican", "yucatan"],
      prepBest: ["fresh", "fermented", "dried"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "orange"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|westcoastseeds.com",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: true,
      vendorSeedList: "WestCoastSeeds",
      vendorVarietyNames: "Habanero",
    },
    {
      id: 12,
      name: "Habanero Chocolate",
      alternateNames: "Black Congo, Brown Habanero",
      species: "chinense",
      type: "habanero_type",
      description: "Among the hottest habanero varieties with rich, earthy, almost coffee-like undertones. Dark brown/chocolate color when ripe. Longer growing season than orange types. Smoky flavor makes exceptional jerk sauce.",
      heatSHU_min: 150000,
      heatSHU_max: 325000,
      heatCategory: "very_hot",
      sweetness: 3,
      fruitiness: 6,
      smokiness: 7,
      bitterness: 4,
      earthiness: 7,
      bestUses: ["hot_sauce", "cooking", "fermenting"],
      cuisineAffinity: ["caribbean", "jamaican"],
      prepBest: ["fresh", "fermented", "dried"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 130,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "brown"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "SeedSow",
      vendorVarietyNames: "Pepper (Hot) - Habanero Chocolate",
    },
    {
      id: 13,
      name: "Habanero Lemon",
      alternateNames: "Lemon Habanero",
      species: "chinense",
      type: "habanero_type",
      description: "Bright yellow habanero with distinctive citrus notes complementing the fruity heat. Slightly less hot than orange but with more complex flavor. Beautiful in light-colored hot sauces and seafood dishes.",
      heatSHU_min: 100000,
      heatSHU_max: 300000,
      heatCategory: "very_hot",
      sweetness: 4,
      fruitiness: 8,
      smokiness: 2,
      bitterness: 2,
      earthiness: 2,
      bestUses: ["hot_sauce", "cooking", "fresh_eating"],
      cuisineAffinity: ["caribbean", "tropical"],
      prepBest: ["fresh", "fermented", "sauce"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 5,
      wallThickness: "thin",
      colorStages: ["green", "yellow"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "SeedSow",
      vendorVarietyNames: "Pepper (Hot) - Habanero Lemon",
    },
    {
      id: 38,
      name: "Scotch Bonnet",
      alternateNames: "Bonney Pepper, Caribbean Red",
      species: "chinense",
      type: "habanero_type",
      description: "Jamaica's signature pepper, similar to habanero but with a distinctive 'tam o'shanter' shape. Sweeter, fruitier flavor essential for authentic jerk seasoning. The Caribbean wouldn't be the same without it.",
      heatSHU_min: 100000,
      heatSHU_max: 350000,
      heatCategory: "very_hot",
      sweetness: 5,
      fruitiness: 8,
      smokiness: 2,
      bitterness: 2,
      earthiness: 3,
      bestUses: ["hot_sauce", "jerk", "cooking"],
      cuisineAffinity: ["caribbean", "jamaican"],
      prepBest: ["fresh", "sauce", "fermented"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 5,
      wallThickness: "thin",
      colorStages: ["green", "yellow", "orange", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|westcoastseeds.com",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: true,
      vendorSeedList: "WestCoastSeeds",
      vendorVarietyNames: "Scotch Bonnet",
    },
    {
      id: 80,
      name: "Fatalii",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "African habanero-type with remarkable citrus/lemon flavor that shines through the extreme heat. Bright yellow pods with intensely fruity aroma. One of the most flavorful superhots - a hot sauce maker's dream.",
      heatSHU_min: 125000,
      heatSHU_max: 325000,
      heatCategory: "extreme",
      sweetness: 4,
      fruitiness: 9,
      smokiness: 2,
      bitterness: 2,
      earthiness: 3,
      bestUses: ["hot_sauce", "cooking", "fermenting"],
      cuisineAffinity: ["african", "global"],
      prepBest: ["fresh", "fermented", "dried"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 5,
      lengthCm_max: 9,
      wallThickness: "thin",
      colorStages: ["green", "yellow"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 96,
      name: "Datil",
      alternateNames: "Datil Pepper",
      species: "chinense",
      type: "habanero_type",
      description: "St. Augustine, Florida's local treasure with mysterious origins. Sweet, fruity flavor reminiscent of habanero but with unique tangy notes. Makes the famous Datil hot sauce. Rarely found outside Florida.",
      heatSHU_min: 100000,
      heatSHU_max: 300000,
      heatCategory: "very_hot",
      sweetness: 6,
      fruitiness: 8,
      smokiness: 2,
      bitterness: 2,
      earthiness: 3,
      bestUses: ["hot_sauce", "cooking", "jelly"],
      cuisineAffinity: ["florida", "american"],
      prepBest: ["fresh", "sauce", "jelly"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 5,
      wallThickness: "thin",
      colorStages: ["green", "yellow", "orange"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },

    // ===== EXTREME PEPPERS (500,000+ SHU) =====
    {
      id: 11,
      name: "Ghost Pepper",
      alternateNames: "Bhut Jolokia, Naga Jolokia",
      species: "chinense",
      type: "habanero_type",
      description: "The pepper that started the superhot craze - first to break 1 million SHU. From Northeast India where it's used sparingly in curries and as elephant deterrent. Slow, creeping heat that builds and builds. Handle with extreme caution.",
      heatSHU_min: 855000,
      heatSHU_max: 1041427,
      heatCategory: "extreme",
      sweetness: 3,
      fruitiness: 6,
      smokiness: 5,
      bitterness: 4,
      earthiness: 5,
      bestUses: ["hot_sauce", "cooking", "drying"],
      cuisineAffinity: ["indian", "global"],
      prepBest: ["dried", "powdered", "sauce"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 6,
      lengthCm_max: 9,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "Long germination time",
      sources: "pepperscale.com|wikipedia.org|seedsnow.com|westcoastseeds.com",
      confidence: "high",
      availableFrom_SeedSow: true,
      availableFrom_WestCoastSeeds: true,
      vendorSeedList: "SeedSow|WestCoastSeeds",
      vendorVarietyNames: "Ghost|Pepper (Hot) - Ghost Chili / Bhut Jolokia",
    },
    {
      id: 39,
      name: "Carolina Reaper",
      alternateNames: "HP22B",
      species: "chinense",
      type: "habanero_type",
      description: "Former Guinness World Record holder (2013-2023) for hottest pepper, bred in South Carolina. Distinctive wrinkled skin and scorpion-like tail. Surprisingly fruity, sweet flavor beneath the apocalyptic heat. Not for the faint of heart.",
      heatSHU_min: 1400000,
      heatSHU_max: 2200000,
      heatCategory: "extreme",
      sweetness: 4,
      fruitiness: 7,
      smokiness: 3,
      bitterness: 3,
      earthiness: 3,
      bestUses: ["hot_sauce", "drying", "challenges"],
      cuisineAffinity: ["global"],
      prepBest: ["dried", "powder", "sauce"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 5,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "Long germination, needs heat mat",
      sources: "pepperscale.com|wikipedia.org|westcoastseeds.com|guinnessworldrecords.com",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: true,
      vendorSeedList: "WestCoastSeeds",
      vendorVarietyNames: "Carolina Reaper",
    },
    {
      id: 41,
      name: "Trinidad Moruga Scorpion",
      alternateNames: "Moruga Scorpion",
      species: "chinense",
      type: "habanero_type",
      description: "Former world record holder from Trinidad with stinging heat that sneaks up on you. Golf ball-sized pods with wrinkled, scorpion-tail appearance. Surprisingly sweet and fruity flavor for such extreme heat. A chilihead favorite.",
      heatSHU_min: 1200000,
      heatSHU_max: 2009231,
      heatCategory: "extreme",
      sweetness: 5,
      fruitiness: 7,
      smokiness: 3,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["caribbean", "global"],
      prepBest: ["dried", "powder", "fermented"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "Long germination time",
      sources: "pepperscale.com|wikipedia.org|westcoastseeds.com",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: true,
      vendorSeedList: "WestCoastSeeds",
      vendorVarietyNames: "Trinidad Moruga Scorpion",
    },
    {
      id: 79,
      name: "7 Pot Barrackpore",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "Named for the Trinidad village where it originated and the claim that one pepper can heat 7 pots of stew. Larger and more wrinkled than standard 7 Pot. Fruity flavor with brutal, lasting heat.",
      heatSHU_min: 1000000,
      heatSHU_max: 1500000,
      heatCategory: "extreme",
      sweetness: 3,
      fruitiness: 6,
      smokiness: 4,
      bitterness: 4,
      earthiness: 5,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["caribbean", "global"],
      prepBest: ["dried", "powder", "sauce"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 7,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 83,
      name: "7 Pot Brain Strain",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "Selectively bred 7 Pot variant with distinctive brain-like wrinkled surface. Named by David Capiello who developed it. Fruity sweetness with devastating heat. The wrinkles maximize surface area for more capsaicin.",
      heatSHU_min: 1000000,
      heatSHU_max: 1350000,
      heatCategory: "extreme",
      sweetness: 4,
      fruitiness: 7,
      smokiness: 3,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["global"],
      prepBest: ["dried", "powder", "fermented"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 84,
      name: "7 Pot Douglah",
      alternateNames: "Chocolate 7 Pot",
      species: "chinense",
      type: "habanero_type",
      description: "Often cited as the hottest naturally occurring pepper without selective breeding. Dark brown/chocolate pods with earthy, slightly smoky flavor. The name 'Douglah' refers to people of mixed African-Indian heritage in Trinidad.",
      heatSHU_min: 923889,
      heatSHU_max: 1853986,
      heatCategory: "extreme",
      sweetness: 3,
      fruitiness: 5,
      smokiness: 6,
      bitterness: 4,
      earthiness: 7,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["caribbean", "global"],
      prepBest: ["dried", "powder", "sauce"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "chocolate-brown"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 82,
      name: "Trinidad Scorpion Butch T",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "Former Guinness World Record holder (2011), named after Butch Taylor who grew the record pod. Distinctive tail and wrinkled skin. Intense, immediate heat with surprising sweetness. A benchmark superhot variety.",
      heatSHU_min: 800000,
      heatSHU_max: 1463700,
      heatCategory: "extreme",
      sweetness: 4,
      fruitiness: 6,
      smokiness: 4,
      bitterness: 4,
      earthiness: 4,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["caribbean", "global"],
      prepBest: ["dried", "powder", "fermented"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 85,
      name: "Dorset Naga",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "UK-developed variant of the Naga Morich, selected for stability and heat. Among the first to exceed 1 million SHU officially. Fruity, floral aroma with delayed but devastating heat. Easier to grow than some superhots.",
      heatSHU_min: 900000,
      heatSHU_max: 1500000,
      heatCategory: "extreme",
      sweetness: 3,
      fruitiness: 7,
      smokiness: 3,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["indian", "global"],
      prepBest: ["dried", "sauce", "powder"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 5,
      lengthCm_max: 7,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 81,
      name: "Red Savina",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "The original Guinness World Record holder (1994-2006) before the superhot era. A selectively bred habanero that dominated the record books for 12 years. Clean, fruity heat without the extreme levels of newer varieties.",
      heatSHU_min: 350000,
      heatSHU_max: 577000,
      heatCategory: "extreme",
      sweetness: 4,
      fruitiness: 7,
      smokiness: 3,
      bitterness: 3,
      earthiness: 3,
      bestUses: ["hot_sauce", "cooking", "drying"],
      cuisineAffinity: ["caribbean", "global"],
      prepBest: ["fresh", "sauce", "dried"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 86,
      name: "Infinity Chili",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "UK-bred pepper that briefly held the world record in 2011. Developed by Nick Woods in Grantham, England. Named for seemingly infinite heat. Wrinkled, gnarly pods with typical chinense fruity aroma.",
      heatSHU_min: 1067286,
      heatSHU_max: 1250000,
      heatCategory: "extreme",
      sweetness: 3,
      fruitiness: 6,
      smokiness: 4,
      bitterness: 4,
      earthiness: 4,
      bestUses: ["hot_sauce", "drying", "cooking"],
      cuisineAffinity: ["global"],
      prepBest: ["dried", "powder", "sauce"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 6,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 87,
      name: "Dragon's Breath",
      alternateNames: "",
      species: "chinense",
      type: "habanero_type",
      description: "Welsh pepper that claimed world record heat of 2.48 million SHU in 2017, though not officially verified. Developed by Mike Smith and Nottingham Trent University. Originally bred for medical numbing applications.",
      heatSHU_min: 2480000,
      heatSHU_max: 2480000,
      heatCategory: "extreme",
      sweetness: 2,
      fruitiness: 5,
      smokiness: 4,
      bitterness: 5,
      earthiness: 4,
      bestUses: ["hot_sauce", "drying", "novelty"],
      cuisineAffinity: ["global"],
      prepBest: ["dried", "powder", "tincture"],
      daysToMaturity_min: 100,
      daysToMaturity_max: 150,
      plantHeightCm_min: 60,
      plantHeightCm_max: 120,
      growthHabit: "bushy",
      yieldLevel: "low",
      difficulty: "advanced",
      climateSuitability: "hot",
      heatTolerance: 9,
      coldTolerance: 2,
      containerFriendly: true,
      minPotLiters: 15,
      indoorSuitable: true,
      greenhouseRecommended: true,
      lengthCm_min: 3,
      lengthCm_max: 5,
      wallThickness: "thin",
      colorStages: ["green", "red"],
      diseaseNotes: "Difficult to source authentic seed",
      sources: "pepperscale.com|wikipedia.org|bbc.com",
      confidence: "medium",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },

    // ===== ORNAMENTAL PEPPERS =====
    {
      id: 93,
      name: "Bolivian Rainbow",
      alternateNames: "",
      species: "annuum",
      type: "ornamental",
      description: "Stunning ornamental with edible pods that display purple, yellow, orange, and red simultaneously. Compact plants make excellent container specimens. Pods point upward like little candles. Decent heat for cooking too.",
      heatSHU_min: 10000,
      heatSHU_max: 30000,
      heatCategory: "medium",
      sweetness: 3,
      fruitiness: 4,
      smokiness: 2,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["ornamental", "cooking", "drying"],
      cuisineAffinity: ["global"],
      prepBest: ["fresh", "dried", "decoration"],
      daysToMaturity_min: 70,
      daysToMaturity_max: 90,
      plantHeightCm_min: 30,
      plantHeightCm_max: 60,
      growthHabit: "compact",
      yieldLevel: "high",
      difficulty: "beginner",
      climateSuitability: "temperate",
      heatTolerance: 6,
      coldTolerance: 5,
      containerFriendly: true,
      minPotLiters: 5,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 1,
      lengthCm_max: 3,
      wallThickness: "thin",
      colorStages: ["purple", "yellow", "orange", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 99,
      name: "Black Pearl",
      alternateNames: "",
      species: "annuum",
      type: "ornamental",
      description: "Award-winning ornamental with dramatic black foliage and pearl-like black pods that ripen to red. 2006 All-America Selections winner. Edible but primarily grown for stunning visual appeal. Perfect for containers.",
      heatSHU_min: 10000,
      heatSHU_max: 30000,
      heatCategory: "medium",
      sweetness: 2,
      fruitiness: 3,
      smokiness: 2,
      bitterness: 4,
      earthiness: 5,
      bestUses: ["ornamental", "cooking"],
      cuisineAffinity: ["global"],
      prepBest: ["fresh", "decoration"],
      daysToMaturity_min: 70,
      daysToMaturity_max: 90,
      plantHeightCm_min: 30,
      plantHeightCm_max: 60,
      growthHabit: "compact",
      yieldLevel: "medium",
      difficulty: "beginner",
      climateSuitability: "temperate",
      heatTolerance: 6,
      coldTolerance: 5,
      containerFriendly: true,
      minPotLiters: 5,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 1,
      lengthCm_max: 2,
      wallThickness: "thin",
      colorStages: ["black", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|all-americaselections.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },

    // ===== ADDITIONAL VARIETIES =====
    {
      id: 90,
      name: "Rocoto",
      alternateNames: "Manzano, Locoto, Apple Pepper",
      species: "pubescens",
      type: "other",
      description: "Unique pepper species with black seeds and fuzzy leaves. Apple-shaped pods with thick, juicy flesh. The only pepper that tolerates cooler temperatures. Popular in Andean cuisine for stuffing. Very different from other peppers.",
      heatSHU_min: 30000,
      heatSHU_max: 100000,
      heatCategory: "hot",
      sweetness: 4,
      fruitiness: 7,
      smokiness: 2,
      bitterness: 3,
      earthiness: 4,
      bestUses: ["stuffing", "cooking", "salsa"],
      cuisineAffinity: ["peruvian", "bolivian", "andean"],
      prepBest: ["stuffed", "fresh", "sauce"],
      daysToMaturity_min: 120,
      daysToMaturity_max: 180,
      plantHeightCm_min: 90,
      plantHeightCm_max: 180,
      growthHabit: "tall",
      yieldLevel: "medium",
      difficulty: "advanced",
      climateSuitability: "cool",
      heatTolerance: 4,
      coldTolerance: 8,
      containerFriendly: false,
      minPotLiters: 25,
      indoorSuitable: false,
      greenhouseRecommended: true,
      lengthCm_min: 4,
      lengthCm_max: 7,
      wallThickness: "very_thick",
      colorStages: ["green", "yellow", "orange", "red"],
      diseaseNotes: "Very long germination, needs cool nights",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 72,
      name: "Bulgarian Carrot",
      alternateNames: "",
      species: "annuum",
      type: "other",
      description: "Bright orange, carrot-shaped pepper with fruity, citrusy heat. Crunchy texture makes it great for fresh eating. Prolific producer with good disease resistance. Flavor similar to habanero but much more manageable heat.",
      heatSHU_min: 5000,
      heatSHU_max: 30000,
      heatCategory: "medium",
      sweetness: 5,
      fruitiness: 8,
      smokiness: 2,
      bitterness: 2,
      earthiness: 3,
      bestUses: ["fresh_eating", "hot_sauce", "salsa"],
      cuisineAffinity: ["global", "eastern_european"],
      prepBest: ["raw", "fermented", "pickled"],
      daysToMaturity_min: 70,
      daysToMaturity_max: 85,
      plantHeightCm_min: 60,
      plantHeightCm_max: 90,
      growthHabit: "bushy",
      yieldLevel: "high",
      difficulty: "beginner",
      climateSuitability: "temperate",
      heatTolerance: 6,
      coldTolerance: 5,
      containerFriendly: true,
      minPotLiters: 12,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 8,
      lengthCm_max: 12,
      wallThickness: "medium",
      colorStages: ["green", "orange"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 69,
      name: "Fish Pepper",
      alternateNames: "",
      species: "annuum",
      type: "other",
      description: "Historic African American heirloom from 1870s Philadelphia, traditionally used to season fish and shellfish. Striking variegated foliage and striped pods. Both leaves and fruits show green/white variegation. A Slow Food Ark variety.",
      heatSHU_min: 5000,
      heatSHU_max: 30000,
      heatCategory: "medium",
      sweetness: 3,
      fruitiness: 4,
      smokiness: 3,
      bitterness: 3,
      earthiness: 5,
      bestUses: ["cooking", "seafood", "hot_sauce"],
      cuisineAffinity: ["american", "cajun"],
      prepBest: ["fresh", "sauce", "cream_sauce"],
      daysToMaturity_min: 80,
      daysToMaturity_max: 95,
      plantHeightCm_min: 60,
      plantHeightCm_max: 90,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "temperate",
      heatTolerance: 6,
      coldTolerance: 5,
      containerFriendly: true,
      minPotLiters: 12,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 5,
      lengthCm_max: 8,
      wallThickness: "thin",
      colorStages: ["striped green/white", "striped orange/white", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org|slowfoodusa.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
    {
      id: 92,
      name: "Bishop's Crown",
      alternateNames: "Christmas Bell, Friar's Hat",
      species: "baccatum",
      type: "other",
      description: "Uniquely shaped pepper with three lobes resembling a bishop's mitre or crown. Mild, fruity flavor at the lobes with heat concentrated in the center ribs. Great conversation piece. South American origin.",
      heatSHU_min: 5000,
      heatSHU_max: 30000,
      heatCategory: "medium",
      sweetness: 6,
      fruitiness: 6,
      smokiness: 2,
      bitterness: 2,
      earthiness: 3,
      bestUses: ["stuffing", "fresh_eating", "ornamental"],
      cuisineAffinity: ["south_american"],
      prepBest: ["stuffed", "raw", "pickled"],
      daysToMaturity_min: 90,
      daysToMaturity_max: 120,
      plantHeightCm_min: 90,
      plantHeightCm_max: 150,
      growthHabit: "tall",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "hot",
      heatTolerance: 8,
      coldTolerance: 3,
      containerFriendly: false,
      minPotLiters: 20,
      indoorSuitable: false,
      greenhouseRecommended: true,
      lengthCm_min: 5,
      lengthCm_max: 8,
      wallThickness: "medium",
      colorStages: ["green", "red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
// ===== ID 5: Cascabel =====
{
  id: 5,
  name: "Cascabel",
  alternateNames: "Rattle Chile, Bola Chile",
  species: "annuum",
  type: "other",
  description: "Round, cherry-shaped Mexican chile named 'little rattle' for the sound dried seeds make when shaken. Nutty, slightly smoky flavor with moderate heat. Essential for salsas and table sauces. The unique shape makes it a conversation piece.",
  heatSHU_min: 1500,
  heatSHU_max: 2500,
  heatCategory: "mild",
  sweetness: 4,
  fruitiness: 4,
  smokiness: 5,
  bitterness: 2,
  earthiness: 6,
  bestUses: ["drying", "salsa", "cooking"],
  cuisineAffinity: ["mexican"],
  prepBest: ["dried", "toasted", "sauce"],
  daysToMaturity_min: 80,
  daysToMaturity_max: 95,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 4,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 2,
  lengthCm_max: 4,
  wallThickness: "thin",
  colorStages: ["green", "red", "brown"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 7: Cherry Bomb =====
{
  id: 7,
  name: "Cherry Bomb",
  alternateNames: "Hot Cherry Pepper",
  species: "annuum",
  type: "other",
  description: "Round, cherry-shaped pepper perfect for pickling and stuffing with cheese. Thick walls hold up well to heat. Moderate spice with sweet undertones. A favorite for Italian antipasto platters and stuffed pepper appetizers.",
  heatSHU_min: 2500,
  heatSHU_max: 5000,
  heatCategory: "medium",
  sweetness: 5,
  fruitiness: 5,
  smokiness: 2,
  bitterness: 2,
  earthiness: 4,
  bestUses: ["pickling", "stuffing", "fresh_eating"],
  cuisineAffinity: ["italian", "american"],
  prepBest: ["pickled", "stuffed", "raw"],
  daysToMaturity_min: 65,
  daysToMaturity_max: 80,
  plantHeightCm_min: 45,
  plantHeightCm_max: 60,
  growthHabit: "compact",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 6,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 10,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thick",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org|seedsnow.com",
  confidence: "high",
  availableFrom_SeedSow: true,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "SeedSow",
  vendorVarietyNames: "Pepper (Hot) - Cherry Bomb",
},

// ===== ID 8: Chimayo =====
{
  id: 8,
  name: "Chimayo",
  alternateNames: "Chimayo Chile",
  species: "annuum",
  type: "other",
  description: "New Mexico heirloom from the village of Chimayó, grown for over 400 years. Unique terroir creates distinctive earthy, slightly sweet flavor. Traditional for red chile sauce and ristras. A true heritage variety.",
  heatSHU_min: 4000,
  heatSHU_max: 6000,
  heatCategory: "medium",
  sweetness: 5,
  fruitiness: 4,
  smokiness: 4,
  bitterness: 2,
  earthiness: 8,
  bestUses: ["drying", "cooking", "salsa"],
  cuisineAffinity: ["mexican", "southwestern"],
  prepBest: ["dried", "roasted", "powder"],
  daysToMaturity_min: 80,
  daysToMaturity_max: 95,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "temperate",
  heatTolerance: 8,
  coldTolerance: 4,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 12,
  lengthCm_max: 18,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|nmsu.edu|slowfoodusa.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 9: Criolla Sella =====
{
  id: 9,
  name: "Criolla Sella",
  alternateNames: "Aji Criolla",
  species: "baccatum",
  type: "other",
  description: "South American heirloom with bright, fruity flavor characteristic of the baccatum species. Golden-orange pods are perfect for fresh salsas and ceviche. The distinctive citrus notes pair beautifully with seafood.",
  heatSHU_min: 10000,
  heatSHU_max: 30000,
  heatCategory: "medium",
  sweetness: 5,
  fruitiness: 8,
  smokiness: 2,
  bitterness: 2,
  earthiness: 3,
  bestUses: ["salsa", "cooking", "fresh_eating"],
  cuisineAffinity: ["south_american", "peruvian"],
  prepBest: ["fresh", "sauce", "ceviche"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 120,
  plantHeightCm_min: 90,
  plantHeightCm_max: 150,
  growthHabit: "tall",
  yieldLevel: "high",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 8,
  coldTolerance: 3,
  containerFriendly: false,
  minPotLiters: 20,
  indoorSuitable: false,
  greenhouseRecommended: true,
  lengthCm_min: 5,
  lengthCm_max: 10,
  wallThickness: "medium",
  colorStages: ["green", "orange"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "medium",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 15: Habanero Red =====
{
  id: 15,
  name: "Habanero Red",
  alternateNames: "Red Caribbean Habanero",
  species: "chinense",
  type: "habanero_type",
  description: "Classic red-ripening habanero with the signature fruity, floral chinense flavor. Slightly hotter than orange types when fully mature. The brilliant red color makes stunning hot sauces. Caribbean heritage.",
  heatSHU_min: 150000,
  heatSHU_max: 350000,
  heatCategory: "very_hot",
  sweetness: 4,
  fruitiness: 8,
  smokiness: 2,
  bitterness: 3,
  earthiness: 3,
  bestUses: ["hot_sauce", "cooking", "fermenting"],
  cuisineAffinity: ["caribbean", "mexican"],
  prepBest: ["fresh", "fermented", "sauce"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 120,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 6,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org|seedsnow.com",
  confidence: "high",
  availableFrom_SeedSow: true,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "SeedSow",
  vendorVarietyNames: "Pepper (Hot) - Habanero Red",
},

// ===== ID 16: Hatch Green =====
{
  id: 16,
  name: "Hatch Green",
  alternateNames: "Hatch Chile, New Mexico Hatch",
  species: "annuum",
  type: "other",
  description: "The famous chile from Hatch, New Mexico - the 'Chile Capital of the World.' Roasted Hatch chiles are a seasonal obsession in the Southwest. Earthy, slightly sweet with variable heat. Best roasted over open flame.",
  heatSHU_min: 1000,
  heatSHU_max: 8000,
  heatCategory: "medium",
  sweetness: 6,
  fruitiness: 4,
  smokiness: 5,
  bitterness: 2,
  earthiness: 7,
  bestUses: ["roasting", "cooking", "stuffing"],
  cuisineAffinity: ["mexican", "southwestern"],
  prepBest: ["roasted", "stuffed", "sauce"],
  daysToMaturity_min: 75,
  daysToMaturity_max: 90,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 8,
  coldTolerance: 4,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 15,
  lengthCm_max: 23,
  wallThickness: "medium",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|nmsu.edu|hatch-green-chile.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 17: Habanada =====
{
  id: 17,
  name: "Habanada",
  alternateNames: "Heatless Habanero",
  species: "chinense",
  type: "habanero_type",
  description: "Revolutionary heatless habanero that delivers all the tropical, floral flavor without any burn. Bred by Michael Mazourek at Cornell University. Perfect for those who love habanero flavor but can't handle the heat.",
  heatSHU_min: 0,
  heatSHU_max: 0,
  heatCategory: "none",
  sweetness: 7,
  fruitiness: 9,
  smokiness: 2,
  bitterness: 1,
  earthiness: 2,
  bestUses: ["fresh_eating", "salsa", "cooking"],
  cuisineAffinity: ["caribbean", "global"],
  prepBest: ["raw", "sauce", "salsa"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 100,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 8,
  coldTolerance: 3,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green", "orange"],
  diseaseNotes: "",
  sources: "pepperscale.com|cornell.edu|johnnyseeds.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 21: Jalapeno Mucho Nacho =====
{
  id: 21,
  name: "Jalapeno Mucho Nacho",
  alternateNames: "Mucho Nacho",
  species: "annuum",
  type: "jalapeno_type",
  description: "Extra-large jalapeño bred for maximum size - up to 4 inches long. Perfect for stuffing and jalapeño poppers. Same great flavor as standard jalapeño but with more meat. High yields of uniform pods.",
  heatSHU_min: 4000,
  heatSHU_max: 8000,
  heatCategory: "medium",
  sweetness: 4,
  fruitiness: 4,
  smokiness: 3,
  bitterness: 2,
  earthiness: 5,
  bestUses: ["stuffing", "pickling", "fresh_eating"],
  cuisineAffinity: ["mexican", "american"],
  prepBest: ["stuffed", "pickled", "raw"],
  daysToMaturity_min: 68,
  daysToMaturity_max: 78,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "very_high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 8,
  lengthCm_max: 10,
  wallThickness: "thick",
  colorStages: ["green", "red"],
  diseaseNotes: "PVY resistant",
  sources: "pepperscale.com|burpee.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 22: Jalapeno Purple =====
{
  id: 22,
  name: "Jalapeno Purple",
  alternateNames: "Purple Jalapeño",
  species: "annuum",
  type: "jalapeno_type",
  description: "Ornamental and edible jalapeño with striking purple pods that ripen to deep red. Same heat and flavor as green jalapeño but with eye-catching color. Purple foliage adds to the ornamental appeal.",
  heatSHU_min: 2500,
  heatSHU_max: 8000,
  heatCategory: "medium",
  sweetness: 4,
  fruitiness: 4,
  smokiness: 3,
  bitterness: 2,
  earthiness: 5,
  bestUses: ["fresh_eating", "pickling", "ornamental"],
  cuisineAffinity: ["mexican", "american"],
  prepBest: ["raw", "pickled", "decoration"],
  daysToMaturity_min: 75,
  daysToMaturity_max: 85,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 5,
  lengthCm_max: 8,
  wallThickness: "thick",
  colorStages: ["purple", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|rareseeds.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 23: Jalapeno TAM =====
{
  id: 23,
  name: "Jalapeno TAM",
  alternateNames: "TAM Mild Jalapeño",
  species: "annuum",
  type: "jalapeno_type",
  description: "Texas A&M bred mild jalapeño for those who want the flavor without intense heat. About 1/3 the heat of standard jalapeños. Perfect gateway pepper for heat-sensitive eaters. Same great jalapeño flavor.",
  heatSHU_min: 1000,
  heatSHU_max: 3500,
  heatCategory: "medium",
  sweetness: 5,
  fruitiness: 4,
  smokiness: 3,
  bitterness: 2,
  earthiness: 5,
  bestUses: ["fresh_eating", "pickling", "stuffing"],
  cuisineAffinity: ["mexican", "american"],
  prepBest: ["raw", "pickled", "stuffed"],
  daysToMaturity_min: 65,
  daysToMaturity_max: 75,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 6,
  lengthCm_max: 9,
  wallThickness: "thick",
  colorStages: ["green", "red"],
  diseaseNotes: "TMV resistant",
  sources: "pepperscale.com|tamu.edu",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 27: Puya =====
{
  id: 27,
  name: "Puya",
  alternateNames: "Pulla Chile",
  species: "annuum",
  type: "cayenne_type",
  description: "Slender Mexican chile similar to guajillo but smaller and hotter. Complex fruity, slightly licorice flavor. Often used in combination with guajillo for depth. Excellent dried for salsas and adobos.",
  heatSHU_min: 5000,
  heatSHU_max: 8000,
  heatCategory: "medium",
  sweetness: 4,
  fruitiness: 6,
  smokiness: 3,
  bitterness: 2,
  earthiness: 5,
  bestUses: ["drying", "salsa", "cooking"],
  cuisineAffinity: ["mexican"],
  prepBest: ["dried", "toasted", "sauce"],
  daysToMaturity_min: 75,
  daysToMaturity_max: 85,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 4,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 8,
  lengthCm_max: 12,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 28: Rezha Macedonian =====
{
  id: 28,
  name: "Rezha Macedonian",
  alternateNames: "Vezeni Piperki",
  species: "annuum",
  type: "other",
  description: "Striking Eastern European heirloom with deeply ribbed, lantern-shaped pods. Sweet and mildly spicy flavor. Traditional for roasting, stuffing, and drying. The dramatic shape makes it a farmers market standout.",
  heatSHU_min: 1000,
  heatSHU_max: 5000,
  heatCategory: "medium",
  sweetness: 7,
  fruitiness: 5,
  smokiness: 3,
  bitterness: 2,
  earthiness: 4,
  bestUses: ["roasting", "stuffing", "drying"],
  cuisineAffinity: ["eastern_european", "mediterranean"],
  prepBest: ["roasted", "stuffed", "dried"],
  daysToMaturity_min: 80,
  daysToMaturity_max: 95,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "temperate",
  heatTolerance: 6,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 8,
  lengthCm_max: 12,
  wallThickness: "medium",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|rareseeds.com",
  confidence: "medium",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 29: Ring of Fire =====
{
  id: 29,
  name: "Ring of Fire",
  alternateNames: "",
  species: "annuum",
  type: "cayenne_type",
  description: "Prolific cayenne-type developed for container growing and high yields. Slender 4-inch pods pack solid heat with slight fruity notes. Plants are compact but extremely productive. Great for drying and hot sauce.",
  heatSHU_min: 15000,
  heatSHU_max: 25000,
  heatCategory: "medium",
  sweetness: 3,
  fruitiness: 5,
  smokiness: 3,
  bitterness: 2,
  earthiness: 4,
  bestUses: ["drying", "hot_sauce", "cooking"],
  cuisineAffinity: ["asian", "global"],
  prepBest: ["dried", "fresh", "fermented"],
  daysToMaturity_min: 60,
  daysToMaturity_max: 75,
  plantHeightCm_min: 45,
  plantHeightCm_max: 60,
  growthHabit: "compact",
  yieldLevel: "very_high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 8,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 8,
  lengthCm_max: 12,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|johnnyseeds.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 30: Scotch Bonnet Red =====
{
  id: 30,
  name: "Scotch Bonnet Red",
  alternateNames: "Red Scotch Bonnet",
  species: "chinense",
  type: "habanero_type",
  description: "The red-ripening variety of Jamaica's favorite pepper. Classic bonnet shape with intensely fruity, slightly sweeter flavor than orange scotch bonnets. Essential for traditional jerk seasoning and Caribbean hot sauces.",
  heatSHU_min: 100000,
  heatSHU_max: 350000,
  heatCategory: "very_hot",
  sweetness: 5,
  fruitiness: 8,
  smokiness: 2,
  bitterness: 2,
  earthiness: 3,
  bestUses: ["hot_sauce", "jerk", "cooking"],
  cuisineAffinity: ["caribbean", "jamaican"],
  prepBest: ["fresh", "sauce", "fermented"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 120,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org|seedsnow.com",
  confidence: "high",
  availableFrom_SeedSow: true,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "SeedSow",
  vendorVarietyNames: "Pepper (Hot) - Scotch Bonnet Red",
},

// ===== ID 31: Scotch Bonnet Yellow =====
{
  id: 31,
  name: "Scotch Bonnet Yellow",
  alternateNames: "Yellow Scotch Bonnet",
  species: "chinense",
  type: "habanero_type",
  description: "Bright yellow scotch bonnet with slightly different flavor profile than red or orange. More citrusy notes complement the fruity base. Makes beautiful golden-colored hot sauces. Same intense heat as other scotch bonnets.",
  heatSHU_min: 100000,
  heatSHU_max: 350000,
  heatCategory: "very_hot",
  sweetness: 5,
  fruitiness: 8,
  smokiness: 2,
  bitterness: 2,
  earthiness: 2,
  bestUses: ["hot_sauce", "jerk", "cooking"],
  cuisineAffinity: ["caribbean", "jamaican"],
  prepBest: ["fresh", "sauce", "fermented"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 120,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green", "yellow"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org|seedsnow.com",
  confidence: "high",
  availableFrom_SeedSow: true,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "SeedSow",
  vendorVarietyNames: "Pepper (Hot) - Scotch Bonnet Yellow",
},

// ===== ID 37: Habanero White =====
{
  id: 37,
  name: "Habanero White",
  alternateNames: "Peruvian White Habanero",
  species: "chinense",
  type: "habanero_type",
  description: "Rare white-skinned habanero with unique flavor profile - more floral and less fruity than orange varieties. Creamy white pods add novelty to hot sauce collections. Slightly less hot than orange habanero.",
  heatSHU_min: 100000,
  heatSHU_max: 300000,
  heatCategory: "very_hot",
  sweetness: 4,
  fruitiness: 6,
  smokiness: 2,
  bitterness: 2,
  earthiness: 3,
  bestUses: ["hot_sauce", "cooking", "novelty"],
  cuisineAffinity: ["peruvian", "global"],
  prepBest: ["fresh", "sauce", "fermented"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 120,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green", "white"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "medium",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 40: Naga Morich =====
{
  id: 40,
  name: "Naga Morich",
  alternateNames: "Naga Moresh, Serpent Chile",
  species: "chinense",
  type: "habanero_type",
  description: "Bangladeshi cousin of the ghost pepper with similar extreme heat. Slightly fruitier flavor profile than bhut jolokia. Name means 'serpent chile' in Bengali. Popular in Northeast Indian cuisine for its slow-building, intense burn.",
  heatSHU_min: 800000,
  heatSHU_max: 1100000,
  heatCategory: "extreme",
  sweetness: 3,
  fruitiness: 7,
  smokiness: 4,
  bitterness: 3,
  earthiness: 4,
  bestUses: ["hot_sauce", "cooking", "drying"],
  cuisineAffinity: ["indian", "bangladeshi"],
  prepBest: ["dried", "sauce", "powder"],
  daysToMaturity_min: 100,
  daysToMaturity_max: 150,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "advanced",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 5,
  lengthCm_max: 8,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "Long germination time",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 42: Thai Red =====
{
  id: 42,
  name: "Thai Red",
  alternateNames: "Red Thai, Thai Red Chili",
  species: "annuum",
  type: "thai_type",
  description: "Mature red-ripened Thai chile with deeper, slightly sweeter flavor than green. The vibrant red color is traditional for curry pastes. Same intense heat as green Thai peppers. Very productive plants.",
  heatSHU_min: 50000,
  heatSHU_max: 100000,
  heatCategory: "hot",
  sweetness: 3,
  fruitiness: 5,
  smokiness: 2,
  bitterness: 2,
  earthiness: 4,
  bestUses: ["cooking", "curry_paste", "drying"],
  cuisineAffinity: ["thai", "vietnamese", "asian"],
  prepBest: ["fresh", "dried", "paste"],
  daysToMaturity_min: 85,
  daysToMaturity_max: 100,
  plantHeightCm_min: 45,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "very_high",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 8,
  coldTolerance: 3,
  containerFriendly: true,
  minPotLiters: 10,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 3,
  lengthCm_max: 7,
  wallThickness: "thin",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 43: Thai Green =====
{
  id: 43,
  name: "Thai Green",
  alternateNames: "Green Thai, Prik Kee Noo",
  species: "annuum",
  type: "thai_type",
  description: "The classic green Thai chile harvested before ripening. Brighter, more vegetal flavor than red. Essential for green Thai curry. Very compact pods pack serious punch. The standard for Southeast Asian cooking.",
  heatSHU_min: 50000,
  heatSHU_max: 100000,
  heatCategory: "hot",
  sweetness: 2,
  fruitiness: 4,
  smokiness: 1,
  bitterness: 3,
  earthiness: 4,
  bestUses: ["cooking", "curry_paste", "fresh_eating"],
  cuisineAffinity: ["thai", "vietnamese", "asian"],
  prepBest: ["fresh", "paste", "sliced"],
  daysToMaturity_min: 70,
  daysToMaturity_max: 85,
  plantHeightCm_min: 45,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "very_high",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 8,
  coldTolerance: 3,
  containerFriendly: true,
  minPotLiters: 10,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 2,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 71: Beaver Dam =====
{
  id: 71,
  name: "Beaver Dam",
  alternateNames: "",
  species: "annuum",
  type: "other",
  description: "Wisconsin heirloom brought by Hungarian immigrants in 1912. Sweet, mild flavor with thick walls perfect for stuffing. Named after Beaver Dam, Wisconsin. A Slow Food Ark of Taste variety worth preserving.",
  heatSHU_min: 500,
  heatSHU_max: 1000,
  heatCategory: "mild",
  sweetness: 7,
  fruitiness: 5,
  smokiness: 2,
  bitterness: 1,
  earthiness: 4,
  bestUses: ["stuffing", "fresh_eating", "roasting"],
  cuisineAffinity: ["hungarian", "american"],
  prepBest: ["stuffed", "raw", "roasted"],
  daysToMaturity_min: 80,
  daysToMaturity_max: 95,
  plantHeightCm_min: 60,
  plantHeightCm_max: 90,
  growthHabit: "bushy",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 6,
  coldTolerance: 6,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 12,
  lengthCm_max: 18,
  wallThickness: "thick",
  colorStages: ["green", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|slowfoodusa.org|rareseeds.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 74: Santa Fe Grande =====
{
  id: 74,
  name: "Santa Fe Grande",
  alternateNames: "Guero, Yellow Hot",
  species: "annuum",
  type: "other",
  description: "Cone-shaped Southwestern pepper that ripens yellow to orange to red. Mild to medium heat with slightly sweet flavor. Perfect for pickling and fresh use. Very productive and early-maturing.",
  heatSHU_min: 500,
  heatSHU_max: 700,
  heatCategory: "mild",
  sweetness: 6,
  fruitiness: 5,
  smokiness: 2,
  bitterness: 2,
  earthiness: 4,
  bestUses: ["pickling", "fresh_eating", "salsa"],
  cuisineAffinity: ["mexican", "southwestern"],
  prepBest: ["pickled", "raw", "roasted"],
  daysToMaturity_min: 60,
  daysToMaturity_max: 75,
  plantHeightCm_min: 50,
  plantHeightCm_max: 75,
  growthHabit: "bushy",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 7,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 10,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 8,
  lengthCm_max: 12,
  wallThickness: "medium",
  colorStages: ["yellow", "orange", "red"],
  diseaseNotes: "TMV resistant",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 77: NuMex Joe E. Parker =====
{
  id: 77,
  name: "NuMex Joe E. Parker",
  alternateNames: "Joe Parker",
  species: "annuum",
  type: "other",
  description: "New Mexico State University variety developed for machine harvest. Large, uniform pods with consistent mild heat. Perfect for roasting and canning. Named after a legendary New Mexico chile farmer.",
  heatSHU_min: 500,
  heatSHU_max: 2000,
  heatCategory: "mild",
  sweetness: 6,
  fruitiness: 4,
  smokiness: 4,
  bitterness: 2,
  earthiness: 6,
  bestUses: ["roasting", "canning", "stuffing"],
  cuisineAffinity: ["mexican", "southwestern"],
  prepBest: ["roasted", "stuffed", "canned"],
  daysToMaturity_min: 70,
  daysToMaturity_max: 85,
  plantHeightCm_min: 50,
  plantHeightCm_max: 75,
  growthHabit: "bushy",
  yieldLevel: "very_high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 8,
  coldTolerance: 4,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 15,
  lengthCm_max: 20,
  wallThickness: "medium",
  colorStages: ["green", "red"],
  diseaseNotes: "Disease resistant",
  sources: "pepperscale.com|nmsu.edu",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 78: Scotch Bonnet Orange =====
{
  id: 78,
  name: "Scotch Bonnet Orange",
  alternateNames: "Orange Scotch Bonnet",
  species: "chinense",
  type: "habanero_type",
  description: "Classic orange variety of the Jamaican scotch bonnet. Bright citrus and tropical fruit flavors with searing heat. The most traditional color for authentic jerk and Caribbean pepper sauces.",
  heatSHU_min: 100000,
  heatSHU_max: 350000,
  heatCategory: "very_hot",
  sweetness: 5,
  fruitiness: 9,
  smokiness: 2,
  bitterness: 2,
  earthiness: 2,
  bestUses: ["hot_sauce", "jerk", "cooking"],
  cuisineAffinity: ["caribbean", "jamaican"],
  prepBest: ["fresh", "sauce", "fermented"],
  daysToMaturity_min: 90,
  daysToMaturity_max: 120,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "medium",
  difficulty: "intermediate",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green", "orange"],
  diseaseNotes: "",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 91: Aji Charapita =====
{
  id: 91,
  name: "Aji Charapita",
  alternateNames: "Wild Peruvian Pepper",
  species: "chinense",
  type: "other",
  description: "Tiny, pea-sized Peruvian pepper considered the most expensive chile in the world due to hand-harvesting. Bright, citrusy flavor with significant heat. Wild-harvested pods fetch premium prices in gourmet markets.",
  heatSHU_min: 30000,
  heatSHU_max: 100000,
  heatCategory: "hot",
  sweetness: 4,
  fruitiness: 8,
  smokiness: 2,
  bitterness: 2,
  earthiness: 3,
  bestUses: ["cooking", "hot_sauce", "gourmet"],
  cuisineAffinity: ["peruvian", "south_american"],
  prepBest: ["fresh", "dried", "sauce"],
  daysToMaturity_min: 100,
  daysToMaturity_max: 140,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "high",
  difficulty: "advanced",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 12,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 0.5,
  lengthCm_max: 1,
  wallThickness: "thin",
  colorStages: ["green", "yellow"],
  diseaseNotes: "Slow germination",
  sources: "pepperscale.com|wikipedia.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 97: Numex Twilight =====
{
  id: 97,
  name: "NuMex Twilight",
  alternateNames: "",
  species: "annuum",
  type: "ornamental",
  description: "New Mexico State University ornamental with pods ripening through purple, yellow, orange, and red simultaneously. Compact plants loaded with upward-pointing peppers. Edible and quite hot despite ornamental status.",
  heatSHU_min: 30000,
  heatSHU_max: 50000,
  heatCategory: "hot",
  sweetness: 2,
  fruitiness: 4,
  smokiness: 2,
  bitterness: 3,
  earthiness: 4,
  bestUses: ["ornamental", "drying", "cooking"],
  cuisineAffinity: ["global"],
  prepBest: ["fresh", "dried", "decoration"],
  daysToMaturity_min: 75,
  daysToMaturity_max: 90,
  plantHeightCm_min: 30,
  plantHeightCm_max: 45,
  growthHabit: "compact",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 6,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 5,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 1,
  lengthCm_max: 2,
  wallThickness: "thin",
  colorStages: ["purple", "yellow", "orange", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|nmsu.edu",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 98: Medusa =====
{
  id: 98,
  name: "Medusa",
  alternateNames: "",
  species: "annuum",
  type: "ornamental",
  description: "Award-winning ornamental with twisted, snake-like pods that earned its mythological name. 2006 All-America Selections winner. Mild enough for children to safely handle. Perfect windowsill plant.",
  heatSHU_min: 1,
  heatSHU_max: 1000,
  heatCategory: "mild",
  sweetness: 5,
  fruitiness: 4,
  smokiness: 1,
  bitterness: 2,
  earthiness: 3,
  bestUses: ["ornamental", "fresh_eating"],
  cuisineAffinity: ["global"],
  prepBest: ["fresh", "decoration"],
  daysToMaturity_min: 60,
  daysToMaturity_max: 75,
  plantHeightCm_min: 20,
  plantHeightCm_max: 30,
  growthHabit: "compact",
  yieldLevel: "high",
  difficulty: "beginner",
  climateSuitability: "temperate",
  heatTolerance: 6,
  coldTolerance: 5,
  containerFriendly: true,
  minPotLiters: 3,
  indoorSuitable: true,
  greenhouseRecommended: false,
  lengthCm_min: 3,
  lengthCm_max: 6,
  wallThickness: "thin",
  colorStages: ["ivory", "yellow", "orange", "red"],
  diseaseNotes: "",
  sources: "pepperscale.com|all-americaselections.org",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},

// ===== ID 100: Pepper X =====
{
  id: 100,
  name: "Pepper X",
  alternateNames: "",
  species: "chinense",
  type: "habanero_type",
  description: "Current Guinness World Record holder (2023) created by Ed Currie, creator of the Carolina Reaper. Officially measured at 2.69 million SHU. Greenish-yellow pods with wrinkled skin. Extreme caution required - for experienced chiliheads only.",
  heatSHU_min: 2690000,
  heatSHU_max: 2690000,
  heatCategory: "extreme",
  sweetness: 3,
  fruitiness: 5,
  smokiness: 3,
  bitterness: 4,
  earthiness: 4,
  bestUses: ["hot_sauce", "challenges", "novelty"],
  cuisineAffinity: ["global"],
  prepBest: ["extract", "powder", "sauce"],
  daysToMaturity_min: 100,
  daysToMaturity_max: 160,
  plantHeightCm_min: 60,
  plantHeightCm_max: 120,
  growthHabit: "bushy",
  yieldLevel: "low",
  difficulty: "advanced",
  climateSuitability: "hot",
  heatTolerance: 9,
  coldTolerance: 2,
  containerFriendly: true,
  minPotLiters: 15,
  indoorSuitable: true,
  greenhouseRecommended: true,
  lengthCm_min: 3,
  lengthCm_max: 5,
  wallThickness: "thin",
  colorStages: ["green", "yellow-green"],
  diseaseNotes: "Seeds difficult to source",
  sources: "pepperscale.com|guinnessworldrecords.com|hotones.com",
  confidence: "high",
  availableFrom_SeedSow: false,
  availableFrom_WestCoastSeeds: false,
  vendorSeedList: "",
  vendorVarietyNames: "",
},
    {
      id: 64,
      name: "Aleppo",
      alternateNames: "Halaby Pepper, Pul Biber",
      species: "annuum",
      type: "other",
      description: "Syrian heirloom traditionally dried and crushed into flakes. Moderate heat with fruity, cumin-like undertones and slight saltiness. Named for the city of Aleppo. The authentic version is increasingly rare due to conflict.",
      heatSHU_min: 10000,
      heatSHU_max: 23000,
      heatCategory: "medium",
      sweetness: 5,
      fruitiness: 6,
      smokiness: 3,
      bitterness: 2,
      earthiness: 5,
      bestUses: ["drying", "cooking", "finishing"],
      cuisineAffinity: ["middle_eastern", "turkish", "mediterranean"],
      prepBest: ["dried", "flaked", "crushed"],
      daysToMaturity_min: 70,
      daysToMaturity_max: 85,
      plantHeightCm_min: 60,
      plantHeightCm_max: 90,
      growthHabit: "bushy",
      yieldLevel: "medium",
      difficulty: "intermediate",
      climateSuitability: "temperate",
      heatTolerance: 7,
      coldTolerance: 5,
      containerFriendly: true,
      minPotLiters: 12,
      indoorSuitable: true,
      greenhouseRecommended: false,
      lengthCm_min: 8,
      lengthCm_max: 12,
      wallThickness: "thin",
      colorStages: ["green", "burgundy-red"],
      diseaseNotes: "",
      sources: "pepperscale.com|wikipedia.org",
      confidence: "high",
      availableFrom_SeedSow: false,
      availableFrom_WestCoastSeeds: false,
      vendorSeedList: "",
      vendorVarietyNames: "",
    },
  ] satisfies Pepper[],
};