// src/crops/coffee.ts
import type { Coffee, CoffeePreferences } from "../types/coffee";
import { COFFEE_FLAVOR_NOTES } from "./coffeeEnums";

export const coffeeCrop = {
  id: "coffee",
  label: "Coffee",
  flavorNotes: COFFEE_FLAVOR_NOTES,
  defaultPreferences: {
    brewMethod: "No preference",
    roastLevel: "No preference",
    originType: "No preference",
    flavorProfile: [],
    budget: "No preference",
    caffeinePreference: "No preference",
    grindPreference: "No preference",
    organicPreference: "No preference",
    fairTradePreference: "No preference",
    intensityPreference: 5,
  } as CoffeePreferences,
  items: [
    // ─── 1. Lavazza Super Crema ───
    {
      id: 1,
      name: "Super Crema",
      brand: "Lavazza",
      origin: "Brazil, Indonesia, Colombia",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["nutty", "caramel", "chocolatey"],
      brewMethods: ["espresso", "moka_pot", "drip"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 6,
      acidity: 4,
      body: 7,
      description: "A velvety, creamy espresso blend with mild honey and almond notes. One of Lavazza's most popular and versatile blends worldwide.",
      amazonAsin: "B000SDKDM4",
    },
    // ─── 2. Lavazza Qualita Oro ───
    {
      id: 2,
      name: "Qualita Oro",
      brand: "Lavazza",
      origin: "Central America, Brazil",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["fruity", "floral", "caramel"],
      brewMethods: ["espresso", "moka_pot", "pour_over"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 5,
      body: 6,
      description: "Lavazza's flagship blend since 1956. A fragrant, aromatic coffee with fruity notes and a sweet, refined aftertaste.",
      amazonAsin: "B0014CVEH6",
    },
    // ─── 3. illy Classico ───
    {
      id: 3,
      name: "Classico Medium Roast",
      brand: "illy",
      origin: "Brazil, Ethiopia, Guatemala, India",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["caramel", "chocolatey", "floral"],
      brewMethods: ["espresso", "drip", "pour_over", "moka_pot"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 4,
      body: 6,
      description: "A perfectly balanced medium roast with notes of caramel, orange blossom, and jasmine. Smooth and elegant with a lingering sweetness.",
      amazonAsin: "B001E4S05A",
    },
    // ─── 4. illy Intenso ───
    {
      id: 4,
      name: "Intenso Dark Roast",
      brand: "illy",
      origin: "Brazil, Ethiopia, India",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["chocolatey", "caramel", "smoky"],
      brewMethods: ["espresso", "moka_pot", "french_press"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 8,
      acidity: 3,
      body: 9,
      description: "A bold, full-bodied dark roast with deep cocoa notes and a rich, toasty finish. Intense and satisfying for those who like it strong.",
      amazonAsin: "B07NQKL14G",
    },
    // ─── 5. Stumptown Hair Bender ───
    {
      id: 5,
      name: "Hair Bender",
      brand: "Stumptown",
      origin: "Latin America, East Africa",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["citrus", "chocolatey", "caramel"],
      brewMethods: ["espresso", "pour_over", "drip", "aeropress"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 6,
      acidity: 6,
      body: 7,
      description: "Stumptown's flagship blend — sweet and complex with dark chocolate, citrus zest, and caramel notes. A crowd pleaser that works in any brew method.",
      amazonAsin: "B00B5GJMBC",
    },
    // ─── 6. Stumptown Holler Mountain ───
    {
      id: 6,
      name: "Holler Mountain",
      brand: "Stumptown",
      origin: "Latin America, East Africa",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["fruity", "caramel", "nutty"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 5,
      body: 6,
      description: "A versatile, well-rounded blend with toffee sweetness, creamy body, and bright fruit notes. Great for everyday drinking.",
      amazonAsin: "B00B5GP2EY",
    },
    // ─── 7. Blue Bottle Three Africas ───
    {
      id: 7,
      name: "Three Africas",
      brand: "Blue Bottle",
      origin: "Ethiopia, Uganda, Congo",
      roastLevel: "light",
      originType: "blend",
      flavorNotes: ["fruity", "berry", "floral"],
      brewMethods: ["pour_over", "drip", "aeropress"],
      budget: "premium",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 7,
      body: 4,
      description: "A bright, fruit-forward blend showcasing the best of African coffees. Blueberry jam, floral aromatics, and a clean, sparkling finish.",
      amazonAsin: "B071JM3LJ3",
    },
    // ─── 8. Blue Bottle Bella Donovan ───
    {
      id: 8,
      name: "Bella Donovan",
      brand: "Blue Bottle",
      origin: "East Africa, South America",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "berry", "caramel"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "premium",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 5,
      body: 6,
      description: "A balanced, approachable blend with jammy fruit, milk chocolate, and a sweet, lingering finish. One of Blue Bottle's most popular blends.",
      amazonAsin: "B071JM2DT5",
    },
    // ─── 9. Counter Culture Big Trouble ───
    {
      id: 9,
      name: "Big Trouble",
      brand: "Counter Culture",
      origin: "South & Central America",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "caramel", "nutty"],
      brewMethods: ["drip", "pour_over", "espresso", "french_press"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 6,
      acidity: 5,
      body: 7,
      description: "A rich, sweet, full-bodied blend with caramel, milk chocolate, and a smooth finish. Counter Culture's top-selling everyday coffee.",
      amazonAsin: "B07FKQGXSD",
    },
    // ─── 10. Counter Culture Hologram ───
    {
      id: 10,
      name: "Hologram",
      brand: "Counter Culture",
      origin: "Colombia, Ethiopia",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["fruity", "chocolatey", "caramel"],
      brewMethods: ["pour_over", "drip", "aeropress"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 6,
      body: 5,
      description: "A bright, complex blend with stonefruit sweetness, chocolate depth, and a crisp finish. Versatile and dynamic.",
      amazonAsin: "B07FKNQ7GR",
    },
    // ─── 11. Peet's Major Dickason's Blend ───
    {
      id: 11,
      name: "Major Dickason's Blend",
      brand: "Peet's Coffee",
      origin: "Multiple Origins",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["smoky", "chocolatey", "earthy"],
      brewMethods: ["drip", "french_press", "espresso", "cold_brew"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 8,
      acidity: 3,
      body: 9,
      description: "Peet's signature blend — rich, complex, and full-bodied with layers of deep flavor. A bold coffee for those who love dark roasts.",
      amazonAsin: "B001GVISJM",
    },
    // ─── 12. Peet's Big Bang ───
    {
      id: 12,
      name: "Big Bang Medium Roast",
      brand: "Peet's Coffee",
      origin: "Ethiopia, Colombia",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["fruity", "caramel", "chocolatey"],
      brewMethods: ["drip", "pour_over", "aeropress"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 5,
      body: 6,
      description: "A bright, vibrant medium roast with lively fruit notes and a sweet, smooth finish. Peet's take on a lighter, more modern style.",
      amazonAsin: "B07DFF1M2S",
    },
    // ─── 13. Death Wish Coffee ───
    {
      id: 13,
      name: "Death Wish",
      brand: "Death Wish Coffee",
      origin: "India, Peru",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["chocolatey", "nutty", "smoky"],
      brewMethods: ["drip", "french_press", "cold_brew", "espresso"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: true,
      fairTrade: true,
      intensity: 10,
      acidity: 2,
      body: 10,
      description: "Billed as the world's strongest coffee. Exceptionally high caffeine with a bold, smooth dark roast flavor. Not for the faint of heart.",
      amazonAsin: "B006CQ1ZHI",
    },
    // ─── 14. Intelligentsia Black Cat Espresso ───
    {
      id: 14,
      name: "Black Cat Classic Espresso",
      brand: "Intelligentsia",
      origin: "Brazil, Colombia",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "caramel", "nutty"],
      brewMethods: ["espresso", "moka_pot"],
      budget: "premium",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 7,
      acidity: 4,
      body: 8,
      description: "A rich, syrupy espresso blend with dark chocolate, molasses, and roasted almond notes. Designed specifically for espresso extraction.",
      amazonAsin: "B079YB4NV6",
    },
    // ─── 15. Intelligentsia Frequency Blend ───
    {
      id: 15,
      name: "Frequency Blend",
      brand: "Intelligentsia",
      origin: "Central & South America",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["caramel", "chocolatey", "fruity"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "premium",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 5,
      body: 6,
      description: "A crowd-pleasing daily drinker with milk chocolate, toffee, and a hint of bright fruit. Balanced and approachable.",
      amazonAsin: "B079YCJXLZ",
    },
    // ─── 16. Kicking Horse Kick Ass Dark ───
    {
      id: 16,
      name: "Kick Ass Dark Roast",
      brand: "Kicking Horse",
      origin: "Indonesia, Central & South America",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["smoky", "chocolatey", "earthy"],
      brewMethods: ["french_press", "drip", "cold_brew", "espresso"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: true,
      fairTrade: true,
      intensity: 9,
      acidity: 2,
      body: 9,
      description: "A bold, in-your-face dark roast with smoky chocolate, earthy depth, and a heavy body. Organic and Fair Trade certified.",
      amazonAsin: "B00ERI55YI",
    },
    // ─── 17. Kicking Horse Three Sisters Medium ───
    {
      id: 17,
      name: "Three Sisters Medium Roast",
      brand: "Kicking Horse",
      origin: "Central & South America, Africa",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "nutty", "fruity"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: true,
      fairTrade: true,
      intensity: 5,
      acidity: 5,
      body: 6,
      description: "A smooth, balanced medium roast with milk chocolate, stone fruit, and cocoa butter. Organic and Fair Trade — great everyday coffee.",
      amazonAsin: "B00ERI55K8",
    },
    // ─── 18. Ethiopian Yirgacheffe (Volcanica) ───
    {
      id: 18,
      name: "Ethiopian Yirgacheffe",
      brand: "Volcanica Coffee",
      origin: "Ethiopia (Yirgacheffe)",
      roastLevel: "light",
      originType: "single_origin",
      flavorNotes: ["fruity", "floral", "citrus"],
      brewMethods: ["pour_over", "aeropress", "drip"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 3,
      acidity: 8,
      body: 3,
      description: "A classic Ethiopian single origin with jasmine, bergamot, and bright citrus notes. Light-bodied, tea-like, and intensely aromatic.",
      amazonAsin: "B003U5TLHO",
    },
    // ─── 19. Colombian Supremo (Volcanica) ───
    {
      id: 19,
      name: "Colombian Supremo",
      brand: "Volcanica Coffee",
      origin: "Colombia (Huila)",
      roastLevel: "medium",
      originType: "single_origin",
      flavorNotes: ["caramel", "nutty", "chocolatey"],
      brewMethods: ["drip", "pour_over", "french_press", "espresso"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 5,
      acidity: 5,
      body: 7,
      description: "A smooth, well-balanced Colombian single origin with nutty sweetness, caramel, and a clean finish. The quintessential crowd pleaser.",
      amazonAsin: "B003U5TLIU",
    },
    // ─── 20. Lavazza Super Crema Decaf ───
    {
      id: 20,
      name: "Dek Decaf Espresso",
      brand: "Lavazza",
      origin: "Brazil, Vietnam",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["caramel", "chocolatey", "nutty"],
      brewMethods: ["espresso", "moka_pot", "drip"],
      budget: "mid_range",
      caffeineLevel: "decaf",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 3,
      body: 5,
      description: "A smooth, sweet decaf espresso blend with caramel and milk chocolate notes. All the flavor, none of the jitters.",
      amazonAsin: "B08BLYV4VZ",
    },
    // ─── 21. Kicking Horse Decaf ───
    {
      id: 21,
      name: "Decaf Swiss Water Process",
      brand: "Kicking Horse",
      origin: "Central & South America",
      roastLevel: "medium_dark",
      originType: "blend",
      flavorNotes: ["chocolatey", "nutty", "caramel"],
      brewMethods: ["drip", "french_press", "pour_over"],
      budget: "mid_range",
      caffeineLevel: "decaf",
      grindOptions: ["whole_bean"],
      organic: true,
      fairTrade: true,
      intensity: 5,
      acidity: 3,
      body: 7,
      description: "Chemical-free Swiss Water Process decaf with rich chocolate and brown sugar notes. Organic, Fair Trade, and surprisingly full-flavored.",
      amazonAsin: "B00ERI55IU",
    },
    // ─── 22. Cafe Don Pablo Subtle Earth ───
    {
      id: 22,
      name: "Subtle Earth Organic",
      brand: "Cafe Don Pablo",
      origin: "Honduras",
      roastLevel: "medium_dark",
      originType: "single_origin",
      flavorNotes: ["chocolatey", "caramel", "nutty"],
      brewMethods: ["drip", "french_press", "espresso", "cold_brew"],
      budget: "budget",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: true,
      fairTrade: false,
      intensity: 6,
      acidity: 3,
      body: 7,
      description: "An incredibly smooth, low-acid coffee with rich chocolate and honey sweetness. Organic certified and exceptional value for the quality.",
      amazonAsin: "B01I4EF9PU",
    },
    // ─── 23. Stone Street Cold Brew Reserve ───
    {
      id: 23,
      name: "Cold Brew Reserve",
      brand: "Stone Street",
      origin: "Colombia",
      roastLevel: "dark",
      originType: "single_origin",
      flavorNotes: ["chocolatey", "smoky", "nutty"],
      brewMethods: ["cold_brew", "french_press"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 7,
      acidity: 2,
      body: 8,
      description: "Specifically roasted for cold brew extraction. Ultra-smooth, chocolatey, and zero bitterness when steeped cold for 12-24 hours.",
      amazonAsin: "B014M5FJ2Y",
    },
    // ─── 24. Bizzy Organic Cold Brew ───
    {
      id: 24,
      name: "Organic Cold Brew Blend",
      brand: "Bizzy",
      origin: "Peru, Nicaragua, Guatemala",
      roastLevel: "medium_dark",
      originType: "blend",
      flavorNotes: ["caramel", "nutty", "chocolatey"],
      brewMethods: ["cold_brew"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: true,
      fairTrade: false,
      intensity: 6,
      acidity: 2,
      body: 7,
      description: "A smooth, sweet cold brew blend optimized for low-acid cold extraction. Organic certified with caramel and hazelnut notes.",
      amazonAsin: "B0727ZQFL5",
    },
    // ─── 25. Koffee Kult Dark Roast ───
    {
      id: 25,
      name: "Dark Roast Whole Bean",
      brand: "Koffee Kult",
      origin: "Colombia, Guatemala, Brazil",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["chocolatey", "caramel", "smoky"],
      brewMethods: ["espresso", "french_press", "drip", "moka_pot"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 8,
      acidity: 2,
      body: 9,
      description: "A heavy-bodied dark roast with cinnamon, cocoa, and a bold, smooth finish. Freshly roasted and shipped direct.",
      amazonAsin: "B00JSMAQ66",
    },
    // ─── 26. Real Good Coffee French Roast ───
    {
      id: 26,
      name: "French Roast",
      brand: "Real Good Coffee",
      origin: "Central & South America",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["smoky", "earthy", "chocolatey"],
      brewMethods: ["drip", "french_press", "cold_brew", "espresso"],
      budget: "budget",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 9,
      acidity: 1,
      body: 9,
      description: "An ultra-dark French roast with smoky, bold character and a heavy body. Maximum roast intensity at a wallet-friendly price.",
      amazonAsin: "B01KFVKWF8",
    },
    // ─── 27. Lifeboost Medium Roast ───
    {
      id: 27,
      name: "Medium Roast",
      brand: "Lifeboost",
      origin: "Nicaragua",
      roastLevel: "medium",
      originType: "single_origin",
      flavorNotes: ["caramel", "chocolatey", "fruity"],
      brewMethods: ["drip", "pour_over", "aeropress", "french_press"],
      budget: "luxury",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: true,
      fairTrade: true,
      intensity: 4,
      acidity: 2,
      body: 6,
      description: "Shade-grown, spring-water washed, single-origin Nicaraguan coffee. Ultra-low acid, organic, and bird-friendly certified.",
      amazonAsin: "B07W1BQPCS",
    },
    // ─── 28. Stumptown French Roast ───
    {
      id: 28,
      name: "French Roast",
      brand: "Stumptown",
      origin: "Central & South America",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["smoky", "chocolatey", "earthy"],
      brewMethods: ["french_press", "drip", "cold_brew", "espresso"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 9,
      acidity: 2,
      body: 9,
      description: "A traditional French roast with deep, smoky character and bittersweet chocolate notes. Dark and bold with a clean finish.",
      amazonAsin: "B00I0GOBJO",
    },
    // ─── 29. Peet's Decaf Major Dickason's ───
    {
      id: 29,
      name: "Decaf Major Dickason's Blend",
      brand: "Peet's Coffee",
      origin: "Multiple Origins",
      roastLevel: "dark",
      originType: "blend",
      flavorNotes: ["smoky", "chocolatey", "earthy"],
      brewMethods: ["drip", "french_press", "espresso"],
      budget: "mid_range",
      caffeineLevel: "decaf",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 7,
      acidity: 3,
      body: 8,
      description: "The same rich, complex Major Dickason's blend in decaf form. Full-bodied and deeply flavored without the caffeine.",
      amazonAsin: "B001KIE2DO",
    },
    // ─── 30. Eight O'Clock Original ───
    {
      id: 30,
      name: "The Original",
      brand: "Eight O'Clock",
      origin: "Central & South America",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["nutty", "caramel", "chocolatey"],
      brewMethods: ["drip", "french_press", "cold_brew"],
      budget: "budget",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 4,
      body: 5,
      description: "A classic American coffee since 1859. Sweet, well-balanced, and smooth with a clean finish. Excellent value for daily drinking.",
      amazonAsin: "B008YB0L6O",
    },
    // ─── 31. AmazonFresh Colombia ───
    {
      id: 31,
      name: "Colombia Medium Roast",
      brand: "AmazonFresh",
      origin: "Colombia",
      roastLevel: "medium",
      originType: "single_origin",
      flavorNotes: ["nutty", "caramel", "citrus"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "budget",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 5,
      body: 5,
      description: "A clean, balanced Colombian single origin at a budget-friendly price. Mild citrus brightness with nutty sweetness.",
      amazonAsin: "B071K8FZFL",
    },
    // ─── 32. Koa Coffee Estate Medium Roast ───
    {
      id: 32,
      name: "Estate Medium Roast Kona",
      brand: "Koa Coffee",
      origin: "Hawaii (Kona)",
      roastLevel: "medium",
      originType: "single_origin",
      flavorNotes: ["nutty", "caramel", "fruity"],
      brewMethods: ["pour_over", "drip", "aeropress"],
      budget: "luxury",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 5,
      body: 6,
      description: "100% Kona coffee from Hawaii's volcanic slopes. Silky body, bright acidity, and complex nutty-fruit character. A premium single-origin experience.",
      amazonAsin: "B0716GXSHJ",
    },
    // ─── 33. Cafe Britt Costa Rica ───
    {
      id: 33,
      name: "Costa Rica Light Roast",
      brand: "Cafe Britt",
      origin: "Costa Rica (Tarrazu)",
      roastLevel: "light",
      originType: "single_origin",
      flavorNotes: ["citrus", "floral", "caramel"],
      brewMethods: ["pour_over", "aeropress", "drip"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 3,
      acidity: 7,
      body: 4,
      description: "A bright, clean light roast from the famed Tarrazu region. Tangerine acidity, honey sweetness, and a floral aroma.",
      amazonAsin: "B001E50TSG",
    },
    // ─── 34. SF Bay Fog Chaser ───
    {
      id: 34,
      name: "Fog Chaser",
      brand: "San Francisco Bay",
      origin: "Central America, East Africa",
      roastLevel: "medium_dark",
      originType: "blend",
      flavorNotes: ["caramel", "chocolatey", "earthy"],
      brewMethods: ["drip", "french_press", "cold_brew"],
      budget: "budget",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 6,
      acidity: 3,
      body: 7,
      description: "A smooth, rich medium-dark blend with caramel sweetness and a clean finish. Exceptional value and consistent quality.",
      amazonAsin: "B00H25FAEY",
    },
    // ─── 35. Illy Decaf ───
    {
      id: 35,
      name: "Decaffeinato Medium Roast",
      brand: "illy",
      origin: "Brazil, Ethiopia, Guatemala",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["caramel", "floral", "chocolatey"],
      brewMethods: ["espresso", "drip", "moka_pot"],
      budget: "mid_range",
      caffeineLevel: "decaf",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 4,
      body: 5,
      description: "illy's signature balanced profile in decaf form. Natural decaffeination preserves the caramel and floral notes of the original.",
      amazonAsin: "B001E4S04Q",
    },
    // ─── 36. Verena Street Swiss Water Decaf ───
    {
      id: 36,
      name: "Sunday Morning Decaf",
      brand: "Verena Street",
      origin: "Central & South America",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "caramel", "nutty"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "budget",
      caffeineLevel: "decaf",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 3,
      body: 5,
      description: "Swiss Water Process decaf with rich chocolate and caramel notes. Chemical-free decaffeination at a great price.",
      amazonAsin: "B00ZR10XEO",
    },
    // ─── 37. Kicking Horse Half Ass ───
    {
      id: 37,
      name: "Half Ass Medium Roast",
      brand: "Kicking Horse",
      origin: "Central & South America",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "nutty", "caramel"],
      brewMethods: ["drip", "pour_over", "french_press"],
      budget: "mid_range",
      caffeineLevel: "low_caf",
      grindOptions: ["whole_bean"],
      organic: true,
      fairTrade: true,
      intensity: 4,
      acidity: 4,
      body: 6,
      description: "Half the caffeine, all the flavor. A smooth, balanced medium roast for those who want to cut back without giving up great coffee.",
      amazonAsin: "B078YNK4GG",
    },
    // ─── 38. Bones Coffee Electric Unicorn ───
    {
      id: 38,
      name: "Electric Unicorn Fruity Cereal",
      brand: "Bones Coffee",
      origin: "Brazil, Colombia",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["fruity", "caramel", "berry"],
      brewMethods: ["drip", "pour_over", "cold_brew"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean", "pre_ground"],
      organic: false,
      fairTrade: false,
      intensity: 4,
      acidity: 4,
      body: 5,
      description: "A fun, flavored medium roast inspired by fruity cereal. Sweet berry and tropical fruit notes make it a unique, playful coffee.",
      amazonAsin: "B07JZRXZ7Z",
    },
    // ─── 39. Lavazza Gran Espresso ───
    {
      id: 39,
      name: "Gran Espresso",
      brand: "Lavazza",
      origin: "Brazil, East Africa",
      roastLevel: "medium_dark",
      originType: "blend",
      flavorNotes: ["spicy", "chocolatey", "earthy"],
      brewMethods: ["espresso", "moka_pot"],
      budget: "mid_range",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: false,
      fairTrade: false,
      intensity: 8,
      acidity: 3,
      body: 8,
      description: "A full-bodied espresso blend with peppery spice, dark chocolate, and a thick, persistent crema. Italian espresso at its finest.",
      amazonAsin: "B000SDKDM4",
    },
    // ─── 40. Equator Coffees Jaguar Espresso ───
    {
      id: 40,
      name: "Jaguar Espresso",
      brand: "Equator Coffees",
      origin: "Guatemala, Ethiopia",
      roastLevel: "medium",
      originType: "blend",
      flavorNotes: ["chocolatey", "berry", "caramel"],
      brewMethods: ["espresso", "moka_pot", "aeropress"],
      budget: "premium",
      caffeineLevel: "regular",
      grindOptions: ["whole_bean"],
      organic: true,
      fairTrade: true,
      intensity: 7,
      acidity: 4,
      body: 7,
      description: "An award-winning espresso blend with dark chocolate, berry compote, and a sweet caramel finish. Organic and Fair Trade certified.",
      amazonAsin: "B08N5WRQHK",
    },
  ] as Coffee[],
};
